spring:
  datasource:
    url: jdbc:mysql://mysql-container2:3306/mysql-container2
#    url: jdbc:mysql://172.17.0.2:3306/mysql
#    url: jdbc:mysql://localhost:3306/mysql?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: other_user
#    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
#    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.springframework.boot.autoconfigure: ERROR
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  port: 8080

#jwt:
##  header: Authorization
#  secret: 41ea7cfcfb520a099ca9f8443a9c78d370c87f894abc7bfa2c6a016bf36ca20b
##  token-validity-in-seconds: 86400