spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/
    username: root
    password:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Demo
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: here
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug