

spring:
  datasource:
    #    url: jdbc:mysql://127.0.0.1:3306/here
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://odiro-db.c76iac2aowx2.ap-northeast-2.rds.amazonaws.com:3306/odiro_database
    username: admin
    password: odiro2024

  data:
    mongodb:
      uri: mongodb://localhost:27017/Demo
    redis:
      #      host: 172.17.0.2 or redis
#      host: redis
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_schema: here
        show_sql: true
        format_sql: true
  security:
    oauth2:
      kakao:
        client-id: 041c2f4f97b6949e3d0d99a52a15ce33
        redirect_uri: http://localhost:3000/auth
        client-secret: EckGrm5S334npYTY9CxbRkNCPMw6pAUi
        authorization-grant-type: authorization_code
        token-uri: https://kauth.kakao.com/oauth/token
        client-name: Kakao
  mail:
    host: smtp.gmail.com
    port: 587
    username: ohjuyeon2000@gmail.com
    password: j l i m a d c h t s w x a m t t
    properties:
      mail:
        smtp:
          from: ODIRO@gmail.com
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000
server:
  address: 0.0.0.0
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
jwt:
  secret: 7ae96706cd6e6aade43a3b843bb3317f823ab927b64beb8d45558b3ac29f079dd36afe40f1646af31c334ccbb568cfe64b9e4e54a47aa5a5077796eca1e58075
aws:
  s3:
    bucket-name: tennis-upload
  access-key: ${ACCESS_KEY}
  secret-key: ${SECRET_KEY}
  region: ap-northeast-2